[build]
  publish = "build/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'self' http: https: data: blob: 'unsafe-inline'; frame-ancestors 'none'"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Robots-Tag = "noindex"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
